[[oxigraph_server]]
arch = "aarch64"
git-tree-sha1 = "da62c22715bf2162ccc152e741698134ac8939b0"
os = "macos"

    [[oxigraph_server.download]]
    sha256 = "95724e8dd6fbfe6e5bde7f186105a93ad56d5dda9d869b231dd2bd96c99385b7"
    url = "https://github.com/JuliaBinaryWrappers/oxigraph_server_jll.jl/releases/download/oxigraph_server-v0.3.20+0/oxigraph_server.v0.3.20.aarch64-apple-darwin.tar.gz"
[[oxigraph_server]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f07e488da506f133a4d0b4986282142ffc125e1"
libc = "glibc"
os = "linux"

    [[oxigraph_server.download]]
    sha256 = "46ba2b9c5640af13d43f290248705653e0f0d1b80c52dbad9b5b149d3f58818c"
    url = "https://github.com/JuliaBinaryWrappers/oxigraph_server_jll.jl/releases/download/oxigraph_server-v0.3.20+0/oxigraph_server.v0.3.20.aarch64-linux-gnu-cxx11.tar.gz"
[[oxigraph_server]]
arch = "x86_64"
git-tree-sha1 = "3cf7c2f45693798610e74b259aab7138c1696708"
os = "macos"

    [[oxigraph_server.download]]
    sha256 = "635858f1a80cd8ef419e851b7c503d0503b18570b957772d3386e9a9ac41fcbb"
    url = "https://github.com/JuliaBinaryWrappers/oxigraph_server_jll.jl/releases/download/oxigraph_server-v0.3.20+0/oxigraph_server.v0.3.20.x86_64-apple-darwin.tar.gz"
[[oxigraph_server]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83a8999600fbcc2e69c8e98114d85f0e556d63bf"
libc = "glibc"
os = "linux"

    [[oxigraph_server.download]]
    sha256 = "3886d655bddb61b1e6bc8f8c29967555aba95ffb0f9ce98cb613610f7e475307"
    url = "https://github.com/JuliaBinaryWrappers/oxigraph_server_jll.jl/releases/download/oxigraph_server-v0.3.20+0/oxigraph_server.v0.3.20.x86_64-linux-gnu-cxx11.tar.gz"
[[oxigraph_server]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb5c966da2497c3c7a01b0193b6a2815101716c8"
os = "windows"

    [[oxigraph_server.download]]
    sha256 = "41f20a1f985e896d6df969d58ade3f1487669caf82a719c1d6e6f9706b9ee28e"
    url = "https://github.com/JuliaBinaryWrappers/oxigraph_server_jll.jl/releases/download/oxigraph_server-v0.3.20+0/oxigraph_server.v0.3.20.x86_64-w64-mingw32-cxx11.tar.gz"
