[[oxigraph_server]]
arch = "aarch64"
git-tree-sha1 = "320e79cf395cecf05958cfe8af7ceb825d843b9c"
os = "macos"

    [[oxigraph_server.download]]
    sha256 = "ca3a71bb5e6dd26f561a497a7b420aa52200509a37a6df7eb714ea60f38271e0"
    url = "https://github.com/JuliaBinaryWrappers/oxigraph_server_jll.jl/releases/download/oxigraph_server-v0.3.18+0/oxigraph_server.v0.3.18.aarch64-apple-darwin.tar.gz"
[[oxigraph_server]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2fff86c57541d36480425b93fedbce31de2a1461"
libc = "glibc"
os = "linux"

    [[oxigraph_server.download]]
    sha256 = "c7cf191b65c374d691a36bddf188a56889350125e34e15a67b5f751c3b7ab341"
    url = "https://github.com/JuliaBinaryWrappers/oxigraph_server_jll.jl/releases/download/oxigraph_server-v0.3.18+0/oxigraph_server.v0.3.18.aarch64-linux-gnu-cxx11.tar.gz"
[[oxigraph_server]]
arch = "x86_64"
git-tree-sha1 = "8044b64f40ac066da7d29f921a451f3edf948714"
os = "macos"

    [[oxigraph_server.download]]
    sha256 = "eff81de79161b2a2e801e38f8ba4f4d2309348fce64f7e3ad7db12dcc613e70d"
    url = "https://github.com/JuliaBinaryWrappers/oxigraph_server_jll.jl/releases/download/oxigraph_server-v0.3.18+0/oxigraph_server.v0.3.18.x86_64-apple-darwin.tar.gz"
[[oxigraph_server]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ad1b121d83c1c1d1b0181615fb6dff1ecdbdb24"
libc = "glibc"
os = "linux"

    [[oxigraph_server.download]]
    sha256 = "19250f85e431a67de7bcb9d4a0141ddb80e7e10d9339915475e122b6b643af4a"
    url = "https://github.com/JuliaBinaryWrappers/oxigraph_server_jll.jl/releases/download/oxigraph_server-v0.3.18+0/oxigraph_server.v0.3.18.x86_64-linux-gnu-cxx11.tar.gz"
[[oxigraph_server]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc90d06a1d09d15917653bd1222c7202809b1b86"
os = "windows"

    [[oxigraph_server.download]]
    sha256 = "a4d4fe6b58a9d7dc1059322f1e9c690bd7f391e583f2086d17bbc00b2f9dd150"
    url = "https://github.com/JuliaBinaryWrappers/oxigraph_server_jll.jl/releases/download/oxigraph_server-v0.3.18+0/oxigraph_server.v0.3.18.x86_64-w64-mingw32-cxx11.tar.gz"
